include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    directives_ordering: ignore
  exclude:
    - .dart_tool/**
    - build/**

linter:
  rules:
    avoid_print: true
    directives_ordering: true
